name: Delete Packages from Github Registry

on:
  workflow_dispatch:
    inputs:
      packageSemVer:
        description: "Exact version (e.g. '1.0.1', '1.2.3')."
      dryRun:
        type: boolean
        description: "Dry run"
        default: true

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Github packages
        uses: smartsquaregmbh/delete-old-packages@v0.4.0
        with:
          keep: 0
          names: |
            cli
            hub
          dry-run: ${{ github.event.inputs.dryRun }}
