name: Delete Packages from Github Registry

on:
  workflow_dispatch:
    inputs:
      versionExplicit:
        description: "Exact version (e.g. '1.0.1', '1.2.3')."

env:
  PACKAGE_SEM_VER: ${{ github.event.inputs.versionExplicit }}

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Delete PR packages
        uses: smartsquaregmbh/delete-old-packages@v0.4.0
        with:
          version-pattern: "^${{ env.PACKAGE_SEM_VER }}$"
          keep: 0
          names: |
            empty
            cli
            hub
