name: Delete Packages from Github Registry

on:
  workflow_dispatch:
    inputs:
      packageSemVer:
        description: "Exact version (e.g. '1.0.1', '1.2.3')."
      dryRun:
        type: boolean
        description: "Dry run"
        default: true

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Github packages
        uses: smartsquaregmbh/delete-old-packages@v0.4.0
        with:
          version-pattern: "^${{ github.event.inputs.packageSemVer }}$"
          dry-run: ${{ github.event.inputs.dryRun }}
          keep: 0
          names: |
            cli
            empty
            groups
            hub
            util
            analytics-core
            analytics-messages
            analytics-browser
            analytics-node
            amplitude-core
            amplitude-browser
            amplitude-node
            experiment-core
            experiment-browser
            experiment-node
            user
            user-messages
            plugin-segment-analytics-browser
            plugin-launch-darkly-experiment-browser
